import img from './(5).png'

export const ProducrData = [
    {
        "": " ",
        " ": " ",
        "id": "0",
        "sku": "HKJCJ6784",
        "size": ["sm","md","lg","xl"],
        "brand": "Gucci",
        "color": ["red", "blue", "white"],
        "price": "24",
        "title": "Reclaimed Vintage unisex grosgrain belt in purple",
        "images": [img,img,img,img,img],
        "rating": "4.5",
        "details": ["Something for your wrist", "Model number: 1788", "Bracelet strap", "Circular bezel", "Branded dial", "Mixed hour markers", "Date window", "Quartz movement", "Fold-over clasp", "5ATM  water resistant to 50 meters", " (160 feet)", "Think showering and swimming", "2 years manufacturing warranty", "Product will only be refunded if", " returned unworn/unused in its ", "original packaging with all tags and ", "labels attached"],
        "reviews": "45",
        "category": "belt",
        "colorHex": ["#F9E2AF", "#009FBD", "#210062", "#77037B"],
        "thumbnail": img,
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt eaque maxime quas consequuntur nulla mollitia cumque aut itaque ab quae minima dolorem! Repudiandae accusamus ipsum reiciendis sunt eius voluptatem quos similique mollitia sit error nobis ad labore quis. Facere laborum?"
    },
    {
        "": " ",
        " ": " ",
        "id": "0",
        "sku": "HKJCJ6784",
        "size": ["sm","md","lg","xl"],
        "brand": "Gucci",
        "color": ["red", "blue", "white"],
        "price": "24",
        "title": "Reclaimed Vintage unisex grosgrain belt in purple",
        "images": [img,img,img,img,img],
        "rating": "4.5",
        "details": ["Something for your wrist", "Model number: 1788", "Bracelet strap", "Circular bezel", "Branded dial", "Mixed hour markers", "Date window", "Quartz movement", "Fold-over clasp", "5ATM  water resistant to 50 meters", " (160 feet)", "Think showering and swimming", "2 years manufacturing warranty", "Product will only be refunded if", " returned unworn/unused in its ", "original packaging with all tags and ", "labels attached"],
        "reviews": "45",
        "category": "belt",
        "colorHex": ["#F9E2AF", "#009FBD", "#210062", "#77037B"],
        "thumbnail": img,
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt eaque maxime quas consequuntur nulla mollitia cumque aut itaque ab quae minima dolorem! Repudiandae accusamus ipsum reiciendis sunt eius voluptatem quos similique mollitia sit error nobis ad labore quis. Facere laborum?"
    },
    {
        "": " ",
        " ": " ",
        "id": "0",
        "sku": "HKJCJ6784",
        "size": ["sm","md","lg","xl"],
        "brand": "Gucci",
        "color": ["red", "blue", "white"],
        "price": "24",
        "title": "Reclaimed Vintage unisex grosgrain belt in purple",
        "images": [img,img,img,img,img],
        "rating": "4.5",
        "details": ["Something for your wrist", "Model number: 1788", "Bracelet strap", "Circular bezel", "Branded dial", "Mixed hour markers", "Date window", "Quartz movement", "Fold-over clasp", "5ATM  water resistant to 50 meters", " (160 feet)", "Think showering and swimming", "2 years manufacturing warranty", "Product will only be refunded if", " returned unworn/unused in its ", "original packaging with all tags and ", "labels attached"],
        "reviews": "45",
        "category": "belt",
        "colorHex": ["#F9E2AF", "#009FBD", "#210062", "#77037B"],
        "thumbnail": img,
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt eaque maxime quas consequuntur nulla mollitia cumque aut itaque ab quae minima dolorem! Repudiandae accusamus ipsum reiciendis sunt eius voluptatem quos similique mollitia sit error nobis ad labore quis. Facere laborum?"
    },
    {
        "": " ",
        " ": " ",
        "id": "0",
        "sku": "HKJCJ6784",
        "size": ["sm","md","lg","xl"],
        "brand": "Gucci",
        "color": ["red", "blue", "white"],
        "price": "24",
        "title": "Reclaimed Vintage unisex grosgrain belt in purple",
        "images": [img,img,img,img,img],
        "rating": "4.5",
        "details": ["Something for your wrist", "Model number: 1788", "Bracelet strap", "Circular bezel", "Branded dial", "Mixed hour markers", "Date window", "Quartz movement", "Fold-over clasp", "5ATM  water resistant to 50 meters", " (160 feet)", "Think showering and swimming", "2 years manufacturing warranty", "Product will only be refunded if", " returned unworn/unused in its ", "original packaging with all tags and ", "labels attached"],
        "reviews": "45",
        "category": "belt",
        "colorHex": ["#F9E2AF", "#009FBD", "#210062", "#77037B"],
        "thumbnail": img,
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt eaque maxime quas consequuntur nulla mollitia cumque aut itaque ab quae minima dolorem! Repudiandae accusamus ipsum reiciendis sunt eius voluptatem quos similique mollitia sit error nobis ad labore quis. Facere laborum?"
    },
    {
        "": " ",
        " ": " ",
        "id": "0",
        "sku": "HKJCJ6784",
        "size": ["sm","md","lg","xl"],
        "brand": "Gucci",
        "color": ["red", "blue", "white"],
        "price": "24",
        "title": "Reclaimed Vintage unisex grosgrain belt in purple",
        "images": [img,img,img,img,img],
        "rating": "4.5",
        "details": ["Something for your wrist", "Model number: 1788", "Bracelet strap", "Circular bezel", "Branded dial", "Mixed hour markers", "Date window", "Quartz movement", "Fold-over clasp", "5ATM  water resistant to 50 meters", " (160 feet)", "Think showering and swimming", "2 years manufacturing warranty", "Product will only be refunded if", " returned unworn/unused in its ", "original packaging with all tags and ", "labels attached"],
        "reviews": "45",
        "category": "belt",
        "colorHex": ["#F9E2AF", "#009FBD", "#210062", "#77037B"],
        "thumbnail": img,
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt eaque maxime quas consequuntur nulla mollitia cumque aut itaque ab quae minima dolorem! Repudiandae accusamus ipsum reiciendis sunt eius voluptatem quos similique mollitia sit error nobis ad labore quis. Facere laborum?"
    },
    {
        "": " ",
        " ": " ",
        "id": "0",
        "sku": "HKJCJ6784",
        "size": ["sm","md","lg","xl"],
        "brand": "Gucci",
        "color": ["red", "blue", "white"],
        "price": "24",
        "title": "Reclaimed Vintage unisex grosgrain belt in purple",
        "images": [img,img,img,img,img],
        "rating": "4.5",
        "details": ["Something for your wrist", "Model number: 1788", "Bracelet strap", "Circular bezel", "Branded dial", "Mixed hour markers", "Date window", "Quartz movement", "Fold-over clasp", "5ATM  water resistant to 50 meters", " (160 feet)", "Think showering and swimming", "2 years manufacturing warranty", "Product will only be refunded if", " returned unworn/unused in its ", "original packaging with all tags and ", "labels attached"],
        "reviews": "45",
        "category": "belt",
        "colorHex": ["#F9E2AF", "#009FBD", "#210062", "#77037B"],
        "thumbnail": img,
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt eaque maxime quas consequuntur nulla mollitia cumque aut itaque ab quae minima dolorem! Repudiandae accusamus ipsum reiciendis sunt eius voluptatem quos similique mollitia sit error nobis ad labore quis. Facere laborum?"
    },
    {
        "": " ",
        " ": " ",
        "id": "0",
        "sku": "HKJCJ6784",
        "size": ["sm","md","lg","xl"],
        "brand": "Gucci",
        "color": ["red", "blue", "white"],
        "price": "24",
        "title": "Reclaimed Vintage unisex grosgrain belt in purple",
        "images": [img,img,img,img,img],
        "rating": "4.5",
        "details": ["Something for your wrist", "Model number: 1788", "Bracelet strap", "Circular bezel", "Branded dial", "Mixed hour markers", "Date window", "Quartz movement", "Fold-over clasp", "5ATM  water resistant to 50 meters", " (160 feet)", "Think showering and swimming", "2 years manufacturing warranty", "Product will only be refunded if", " returned unworn/unused in its ", "original packaging with all tags and ", "labels attached"],
        "reviews": "45",
        "category": "belt",
        "colorHex": ["#F9E2AF", "#009FBD", "#210062", "#77037B"],
        "thumbnail": img,
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt eaque maxime quas consequuntur nulla mollitia cumque aut itaque ab quae minima dolorem! Repudiandae accusamus ipsum reiciendis sunt eius voluptatem quos similique mollitia sit error nobis ad labore quis. Facere laborum?"
    },
    {
        "": " ",
        " ": " ",
        "id": "0",
        "sku": "HKJCJ6784",
        "size": ["sm","md","lg","xl"],
        "brand": "Gucci",
        "color": ["red", "blue", "white"],
        "price": "24",
        "title": "Reclaimed Vintage unisex grosgrain belt in purple",
        "images": [img,img,img,img,img],
        "rating": "4.5",
        "details": ["Something for your wrist", "Model number: 1788", "Bracelet strap", "Circular bezel", "Branded dial", "Mixed hour markers", "Date window", "Quartz movement", "Fold-over clasp", "5ATM  water resistant to 50 meters", " (160 feet)", "Think showering and swimming", "2 years manufacturing warranty", "Product will only be refunded if", " returned unworn/unused in its ", "original packaging with all tags and ", "labels attached"],
        "reviews": "45",
        "category": "belt",
        "colorHex": ["#F9E2AF", "#009FBD", "#210062", "#77037B"],
        "thumbnail": img,
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt eaque maxime quas consequuntur nulla mollitia cumque aut itaque ab quae minima dolorem! Repudiandae accusamus ipsum reiciendis sunt eius voluptatem quos similique mollitia sit error nobis ad labore quis. Facere laborum?"
    },
    {
        "": " ",
        " ": " ",
        "id": "0",
        "sku": "HKJCJ6784",
        "size": ["sm","md","lg","xl"],
        "brand": "Gucci",
        "color": ["red", "blue", "white"],
        "price": "24",
        "title": "Reclaimed Vintage unisex grosgrain belt in purple",
        "images": [img,img,img,img,img],
        "rating": "4.5",
        "details": ["Something for your wrist", "Model number: 1788", "Bracelet strap", "Circular bezel", "Branded dial", "Mixed hour markers", "Date window", "Quartz movement", "Fold-over clasp", "5ATM  water resistant to 50 meters", " (160 feet)", "Think showering and swimming", "2 years manufacturing warranty", "Product will only be refunded if", " returned unworn/unused in its ", "original packaging with all tags and ", "labels attached"],
        "reviews": "45",
        "category": "belt",
        "colorHex": ["#F9E2AF", "#009FBD", "#210062", "#77037B"],
        "thumbnail": img,
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt eaque maxime quas consequuntur nulla mollitia cumque aut itaque ab quae minima dolorem! Repudiandae accusamus ipsum reiciendis sunt eius voluptatem quos similique mollitia sit error nobis ad labore quis. Facere laborum?"
    },
    {
        "": " ",
        " ": " ",
        "id": "0",
        "sku": "HKJCJ6784",
        "size": ["sm","md","lg","xl"],
        "brand": "Gucci",
        "color": ["red", "blue", "white"],
        "price": "24",
        "title": "Reclaimed Vintage unisex grosgrain belt in purple",
        "images": [img,img,img,img,img],
        "rating": "4.5",
        "details": ["Something for your wrist", "Model number: 1788", "Bracelet strap", "Circular bezel", "Branded dial", "Mixed hour markers", "Date window", "Quartz movement", "Fold-over clasp", "5ATM  water resistant to 50 meters", " (160 feet)", "Think showering and swimming", "2 years manufacturing warranty", "Product will only be refunded if", " returned unworn/unused in its ", "original packaging with all tags and ", "labels attached"],
        "reviews": "45",
        "category": "belt",
        "colorHex": ["#F9E2AF", "#009FBD", "#210062", "#77037B"],
        "thumbnail": img,
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt eaque maxime quas consequuntur nulla mollitia cumque aut itaque ab quae minima dolorem! Repudiandae accusamus ipsum reiciendis sunt eius voluptatem quos similique mollitia sit error nobis ad labore quis. Facere laborum?"
    },
]