import Head from 'next/head'

import Header from '@/components/header/Header'
import Hero from '@/components/hero/Hero'
import Banner from '@/components/banner/Banner'
import Feature from '@/components/feature/Feature'
import Products from '@/components/products/Products'
import Newarrivals from '@/components/newarrivals/Newarrivals'
import Deal from '@/components/deal/Deal'
import Blog from '@/components/blog/Blog'
import Footer from '@/components/footer/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800&display=swap" rel="stylesheet" />
      </Head>
      <main>
        <Header />
        <Hero />
        <Feature/>
        <Products/>
        <Banner/>
        <Newarrivals/>
        <Deal/>
        <Blog/>
        <Footer/>
      </main>
    </>
  )
}
