import { FinisherCellName, SuccessCellName, player1, player2, player3 } from "@/Data/Data";

export const player1DiceTest = [
    {
        id: 0,
        playerName: player1,
        dicesValue: [],
        previousValue: 0,
        currentValue: 0,
        readyAction: false,
        currentCell: { cellName: SuccessCellName, cellId: 0, },
        inHouse: false,
        inMainCell: false,
        inFinisherCell: false,
        inSuccessCell: true,
    },
    {
        id: 1,
        playerName: player1,
        dicesValue: [],
        previousValue: 0,
        currentValue: 0,
        readyAction: false,
        currentCell: { cellName: SuccessCellName, cellId: 1, },
        inHouse: false,
        inMainCell: false,
        inFinisherCell: false,
        inSuccessCell: true,
    },
    {
        id: 2,
        playerName: player1,
        dicesValue: [],
        previousValue: 0,
        currentValue: 0,
        readyAction: false,
        currentCell: { cellName: SuccessCellName, cellId: 2, },
        inHouse: false,
        inMainCell: false,
        inFinisherCell: false,
        inSuccessCell: true,
    },
    {
        id: 3,
        playerName: player1,
        dicesValue: [],
        previousValue: 0,
        currentValue: 0,
        readyAction: false,
        currentCell: { cellName: FinisherCellName, cellId: 4, },
        inHouse: false,
        inMainCell: false,
        inFinisherCell: true,
        inSuccessCell: false,
    },

]

export const player2DiceTest = [
    {
        id: 0,
        playerName: player2,
        dicesValue: [],
        previousValue: 0,
        currentValue: 0,
        readyAction: false,
        currentCell: { cellName: SuccessCellName, cellId: 0, },
        inHouse: false,
        inMainCell: false,
        inFinisherCell: false,
        inSuccessCell: true,
    },
    {
        id: 1,
        playerName: player2,
        dicesValue: [],
        previousValue: 0,
        currentValue: 0,
        readyAction: false,
        currentCell: { cellName: SuccessCellName, cellId: 1, },
        inHouse: false,
        inMainCell: false,
        inFinisherCell: false,
        inSuccessCell: true,
    },
    {
        id: 2,
        playerName: player2,
        dicesValue: [],
        previousValue: 0,
        currentValue: 0,
        readyAction: false,
        currentCell: { cellName: SuccessCellName, cellId: 2, },
        inHouse: false,
        inMainCell: false,
        inFinisherCell: false,
        inSuccessCell: true,
    },
    {
        id: 3,
        playerName: player2,
        dicesValue: [],
        previousValue: 0,
        currentValue: 0,
        readyAction: false,
        currentCell: { cellName: FinisherCellName, cellId: 4, },
        inHouse: false,
        inMainCell: false,
        inFinisherCell: true,
        inSuccessCell: false,
    },

]

export const player3DiceTest = [
    {
        id: 0,
        playerName: player3,
        dicesValue: [],
        previousValue: 0,
        currentValue: 0,
        readyAction: false,
        currentCell: { cellName: SuccessCellName, cellId: 0, },
        inHouse: false,
        inMainCell: false,
        inFinisherCell: false,
        inSuccessCell: true,
    },
    {
        id: 1,
        playerName: player3,
        dicesValue: [],
        previousValue: 0,
        currentValue: 0,
        readyAction: false,
        currentCell: { cellName: SuccessCellName, cellId: 1, },
        inHouse: false,
        inMainCell: false,
        inFinisherCell: false,
        inSuccessCell: true,
    },
    {
        id: 2,
        playerName: player3,
        dicesValue: [],
        previousValue: 0,
        currentValue: 0,
        readyAction: false,
        currentCell: { cellName: SuccessCellName, cellId: 2, },
        inHouse: false,
        inMainCell: false,
        inFinisherCell: false,
        inSuccessCell: true,
    },
    {
        id: 3,
        playerName: player3,
        dicesValue: [],
        previousValue: 0,
        currentValue: 0,
        readyAction: false,
        currentCell: { cellName: FinisherCellName, cellId: 4, },
        inHouse: false,
        inMainCell: false,
        inFinisherCell: true,
        inSuccessCell: false,
    },

]